### ISSUE TITLE
Import of OFFCHAIN_ATTESTATION_VERSION and Offchain seems not to be working atm

### ISSUE THREAD

**Issue by michael-spengler** [ethereum-attestation-service/eas-sdk#77]
Can be tested by trying 

```ts
import { OFFCHAIN_ATTESTATION_VERSION, Offchain  } from "@ethereum-attestation-service/eas-sdk"
```
as recommended here: 
https://github.com/ethereum-attestation-service/eas-sdk#verify-an-offchain-attestation

**Comment by monique-baumann** [comment]
@slavik0329: once this is fixed, I can further improve https://deno.land/x/ethereum_attestation_service 

If you want [the deno module](https://deno.land/x/ethereum_attestation_service) in your org, let me know. I can transfer it if you wish.

Btw. Deno is cool. You might give it a chance.

**Comment by lbeder** [comment]
> https://github.com/ethereum-attestation-service/eas-sdk#verify-an-offchain-attestation

The README.md was updated here: 8177f39dd1b38814954242813975ab2487b58cdd. Please use `OffChainAttestationVersion` instead.  

What issue are you having with importing `Offchain`?

**Comment by michael-spengler** [comment]
> > https://github.com/ethereum-attestation-service/eas-sdk#verify-an-offchain-attestation
> 
> The README.md was updated here: [8177f39](https://github.com/ethereum-attestation-service/eas-sdk/commit/8177f39dd1b38814954242813975ab2487b58cdd). Please use `OffChainAttestationVersion` instead.

Thank You. Will try it.
> 
> What issue are you having with importing `Offchain`?
... does not export ... called Offchain. Will look into it later again. Maybe due to strict typescript checks...

**Comment by monique-baumann** [comment]
@lbeder: have you also planned to introduce: 

**Interchain Attestations**

This would be amazing imo - especially in times when the numbers of layer 2s grow like weed. :)

**Comment by michael-spengler** [comment]
> @lbeder: have you also planned to introduce:
> 
> **Interchain Attestations**
> 
> This would be amazing imo - especially in times when the numbers of layer 2s grow like weed. :)

Yeah. The EAS could facilitate reliable cross chain communications... This would boost many cool projects like Interchain Investment DAOs, Freedom Enterprises etc.

**Comment by monique-baumann** [comment]
Attestations could be like: 
Contract on Chain X has the following state at block.timestamp ...

**Comment by monique-baumann** [comment]
> OffChainAttestationVersion

> > https://github.com/ethereum-attestation-service/eas-sdk#verify-an-offchain-attestation
> 
> The README.md was updated here: [8177f39](https://github.com/ethereum-attestation-service/eas-sdk/commit/8177f39dd1b38814954242813975ab2487b58cdd). Please use `OffChainAttestationVersion` instead.
>
@lbeder The commit you have mentioned is about something else imo. 
I confirm the error persists with "OffChainAttestationVersion" atm. Error message: The requested module 'npm:@ethereum-attestation-service/eas-sdk' does not provide an export named 'OffChainAttestationVersion'
> What issue are you having with importing `Offchain`?
same with "Offchain": 
The requested module 'npm:@ethereum-attestation-service/eas-sdk' does not provide an export named 'Offchain'

Everything else in the sdk seems to work perfectly fine with deno ... :+1:

**Comment by lbeder** [comment]
> > OffChainAttestationVersion
> 
> > > https://github.com/ethereum-attestation-service/eas-sdk#verify-an-offchain-attestation
> > 
> > 
> > The README.md was updated here: [8177f39](https://github.com/ethereum-attestation-service/eas-sdk/commit/8177f39dd1b38814954242813975ab2487b58cdd). Please use `OffChainAttestationVersion` instead.
> 
> @lbeder The commit you have mentioned is about something else imo. I confirm the error persists with "OffChainAttestationVersion" atm. Error message: The requested module 'npm:@ethereum-attestation-service/eas-sdk' does not provide an export named 'OffChainAttestationVersion'
> 
> > What issue are you having with importing `Offchain`?
> > same with "Offchain":
> > The requested module 'npm:@ethereum-attestation-service/eas-sdk' does not provide an export named 'Offchain'
> 
> Everything else in the sdk seems to work perfectly fine with deno ... 👍

I've published a new version that fixes the lowercase typo (it should be `OffchainAttestationVersion` instead of `OffChainAttestationVersion`). Please check it out.

I'm not familiar with the Deno module, but I'd suggest to continue the discussion about in our telegram group.

**Comment by monique-baumann** [comment]
thanks - currently the only error which still exists imo is:
![Screenshot from 2024-01-08 21-49-45](https://github.com/ethereum-attestation-service/eas-sdk/assets/145258627/7cc02c91-f9dc-43b8-b76a-15a6b115cb35)

**Comment by monique-baumann** [comment]
> Offchain



> thanks - currently the only error which still exists imo is: ![Screenshot from 2024-01-08 21-49-45](https://private-user-images.githubusercontent.com/145258627/295033066-7cc02c91-f9dc-43b8-b76a-15a6b115cb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NDczNzcsIm5iZiI6MTcwNDc0NzA3NywicGF0aCI6Ii8xNDUyNTg2MjcvMjk1MDMzMDY2LTdjYzAyYzkxLWY5ZGMtNDNiOC1iNzZhLTE1YTZiMTE1Y2IzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQyMDUxMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWM3Y2RjOWU0NWFiNWE0ODY2MmMzNTk3MTU1MGM2NDYyZmU3NTc4YTBkN2EzMjQ1NTM2ZWQ4OWM4YWMzNmQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g1aC9A2tIh1JHE7kR8VFCedXCeYsjij8tG8oBaPyPQc)

while https://github.com/monique-baumann/deno-eas/blob/main/src/deno-eas.ts#L1 

We might also look into it on Wednesday. If we find a solution we'll share it. 
Thank you for the EAS ...

**Comment by lbeder** [comment]
This doesn't seem to be an issue with the SDK itself, but rather how it's being (re)built by an external framework
